### ISSUE TITLE
examples and questions...

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-customize-design#4]
... specifically related to mobile -- in case this helps with thinking about what we/you want to include. :-)

Thread starts here: https://webaim.org/discussion/mail_thread?thread=9105

**Comment by iamjolly** [comment]
I've made a number of edits to this and would love feedback to further refine if needed @slhenry.

Page can be previewed at: https://w3c.github.io/wai-customize-design/meta/customize/

**Comment by slhenry** [comment]
awesome!

closing this for now. if specific suggestions, please open new issue.
